### ISSUE TITLE
macOS portable version does not launch properly

### ISSUE THREAD

**Issue by n9yty** [digital195/unifi-protect-viewer#5]
Runniung a new install on macOS Ventura 13.4, this is the 'portable' release:

```
Uncaught Exception:
Error: ENOENT: no such file or directory, mkdir '/store'
at Object.mkdirSync (node:fs:1349:3)
at ElectronStore._ensureDirectory (/Applications/unifi-protect-viewer.app/Contents/Resources/app/node_modules/conf/dist/source/index.js:358:12)
at get store [as store] (/Applications/unifi-protect-viewer.app/Contents/Resources/app/node_modules/conf/dist/source/index.js:284:22)
at new Conf (/Applications/unifi-protect-viewer.app/Contents/Resources/app/node_modules/conf/dist/source/index.js:131:32)
at new ElectronStore (/Applications/unifi-protect-viewer.app/Contents/Resources/app/node_modules/electron-store/index.js:69:3)
at Object.<anonymous> (/Applications/unifi-protect-viewer.app/Contents/Resources/app/main.js:24:26)
at Module._compile (node:internal/modules/cjs/loader:1120:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
```

The other (non-portable) version works fine.

**Comment by digital195** [comment]
What kind of architecture does your Macbook/ System have?

The current version is only tested with Intel processors. 

Can you test this version to see if it runs? I have attached it to the release, if the version runs I will upload the changes to the repository in a few days. It is a version built for the Apple Silicon architecture

https://github.com/digital195/unifi-protect-viewer/releases/download/v0.1.0/unifi-protect-viewer-darwin-arm64-portable.zip

**Comment by n9yty** [comment]
It was on an Intel mac. 16" 2019 MacBook Pro running macOS 13.4.1.  The version you posted above is just Apple Silicon so I can't test it.

**Comment by digital195** [comment]
then could you test this version?

https://github.com/digital195/unifi-protect-viewer/releases/download/v0.1.1/unifi-protect-viewer-darwin-x64-0.1.1-portable.zip

otherwise i can not help you, cause i don't own a macbook with an intel processor any more.
